FROM tomcat:9.0.30-jdk8-openjdk
ARG WAR=target/api-0.0.2-SNAPSHOT.war
RUN apt update && apt install maven && apt clean 
COPY /code /project
WORKDIR /code
RUN mvn clean install && cp ${WAR} /usr/local/tomcat/webapps/ROOT.war && rm -r ~/.m2
EXPOSE 8080