ARG WAR=target/api-0.0.1-SNAPSHOT.war
FROM arm64v8/maven:3.6.3-jdk-11-slim as build
WORKDIR /project
COPY ./code /project
RUN mvn clean install

FROM tomcat:9.0.30-jdk8-openjdk
ARG WAR
COPY --from=buildstage /project/${WAR} /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080